_target_: pc_sam.model.pc_sam.PointCloudSAM
pc_encoder:
  _target_: pc_sam.model.pc_encoder.PointCloudEncoder
  patch_embed:
    _target_: pc_sam.model.pc_encoder.PatchEmbed
    in_channels: 6
    out_channels: 512  # compatible with unit3d-l
    # num_patches: 1024
    # patch_size: 256
    num_patches: 128
    patch_size: 32
  transformer:
    _target_: timm.create_model
    model_name: eva02_large_patch14_448
    pretrained: False
  embed_dim: 256
mask_encoder:
  _target_: pc_sam.model.prompt_encoder.MaskEncoder
  embed_dim: 256
mask_decoder:
  _target_: pc_sam.model.mask_decoder.MaskDecoder
  transformer_dim: 256
  transformer:
    _target_: pc_sam.model.transformer.TwoWayTransformer
    depth: 2
    embedding_dim: 256
    num_heads: 8
    mlp_dim: 2048
prompt_iters: 5
