defaults:
  - model: base
  - dataset@train_dataset: mixture
  - dataset@val_dataset: partnet_val
  - loss: default
  - _self_

# Global variables
num_samples: 10000

# For 24GB GPU
train_dataloader:
  batch_size: 4
  num_workers: 8
  shuffle: True
  drop_last: True

val_freq: 5
val_dataloader:
  batch_size: 16
  num_workers: 16
  shuffle: False
  drop_last: False

lr: 3e-4
weight_decay: 1e-4
max_grad_value: 1.0
gradient_accumulation_steps: 1
save_freq: 5

scheduler:
  _target_: pc_sam.optim.WarmupMultiStepLR
  milestones: [40000, 50000]
  warmup_iters: 2000
  warmup_factor: 0.001
  gamma: 0.1

pretrained_ckpt_path: ./pretrained/uni3d-b/model.pt
max_epochs: 10000
max_steps: 5000000

# Logging
run_name: base_mixture
project_dir: "./logs/${run_name}"
log_with: wandb
