defaults:
  - model: default
  - dataset@train_dataset: partnet 
  - dataset@val_dataset: partnet_val
  - loss: default

# Global variables
num_samples: 10000

# For 24GB GPU
train_dataloader:
  batch_size: 2
  num_workers: 8
  shuffle: True
  drop_last: True

val_freq: 5
val_dataloader:
  batch_size: 16
  num_workers: 16
  shuffle: False
  drop_last: False

lr: 3e-4
weight_decay: 0.1
max_grad_value: 1.0
gradient_accumulation_steps: 1
save_freq: 5

scheduler:
  _target_: pc_sam.optim.WarmupMultiStepLR
  milestones: [400000, 500000]
  warmup_iters: 3000
  warmup_factor: 0.001
  gamma: 0.1

pretrained_ckpt_path: ./pretrained/uni3d-l/model.pt
max_epochs: 10000
max_steps: 5000000

# Logging
run_name: default_partnet+scannet_block
project_dir: "./logs/${run_name}"
log_with: wandb
